git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Algorithms.Benchmarks.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Algorithms.DataAnalysis.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Analysis.Statistics.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Analysis.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Access
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Access.Administration
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Access.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Common
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Administrator
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.JobManager
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave.App
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave.ConsoleClient
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave.TrayIcon
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Slave.WindowsService
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.Hive.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.OKB
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Clients.OKB.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.CodeEditor
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Core.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Data.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.DataPreprocessing.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.DebugEngine.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Encodings.PermutationEncoding.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Encodings.ScheduleEncoding.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Encodings.SymbolicExpressionTreeEncoding.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.ExactOptimization
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.ExactOptimization.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.MainForm
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.MainForm.WindowsForms
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Operators.Programmable.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Operators.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Operators.Views.GraphVisualization
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Operators.Views.GraphVisualization.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Optimization.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Optimizer
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.ParallelEngine.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Parameters.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Persistence.GUI
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.BinPacking.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Symbolic.Classification.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Symbolic.Regression.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Symbolic.TimeSeriesPrognosis.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Symbolic.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Trading.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.DataAnalysis.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.ExternalEvaluation
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.ExternalEvaluation.GP
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.ExternalEvaluation.Matlab
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.ExternalEvaluation.Scilab
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.ExternalEvaluation.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.GeneticProgramming.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Instances.DataAnalysis.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Instances.TSPLIB.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Instances.VehicleRouting.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Instances.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Knapsack.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.LinearAssignment.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Orienteering.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Programmable.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.PTSP.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.QuadraticAssignment.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.Scheduling.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.TestFunctions.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.TravelingSalesman.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Problems.VehicleRouting.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Scripting.Views
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Access
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Access.DataAccess
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Deployment
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Deployment.DataAccess
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Hive
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Hive.DataAccess
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Hive.JanitorService
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.Hive.Web
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.OKB
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.OKB.DataAccess
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.WebApp
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.WebApp.Maintenance
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.WebApp.Statistics
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Services.WebApp.Status
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Tests
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\HeuristicLab.Visualization.ChartControlsExtensions
git rm -r C:\Users\P41847\Documents\GitHub\HeuristicLab\Installers